// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_VYRcjkObUnT5ARTM7e4Rvw7Cyug5ho',
    appId: '1:1021851511933:web:a2afc8941f1636fcaf1514',
    messagingSenderId: '1021851511933',
    projectId: 'eliassprinksens',
    authDomain: 'eliassprinksens.firebaseapp.com',
    storageBucket: 'eliassprinksens.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVe_1CiW31Ag0Gud2Y5JOcU3DnEYi5Nxo',
    appId: '1:1021851511933:android:2156fdf3357c4cf7af1514',
    messagingSenderId: '1021851511933',
    projectId: 'eliassprinksens',
    storageBucket: 'eliassprinksens.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5K4Pj5k-K6iFmI6gZpCvDFw77mQsqp_E',
    appId: '1:1021851511933:ios:b3982a1a1eb3a8efaf1514',
    messagingSenderId: '1021851511933',
    projectId: 'eliassprinksens',
    storageBucket: 'eliassprinksens.firebasestorage.app',
    iosBundleId: 'com.example.sprinkSenseSmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5K4Pj5k-K6iFmI6gZpCvDFw77mQsqp_E',
    appId: '1:1021851511933:ios:b3982a1a1eb3a8efaf1514',
    messagingSenderId: '1021851511933',
    projectId: 'eliassprinksens',
    storageBucket: 'eliassprinksens.firebasestorage.app',
    iosBundleId: 'com.example.sprinkSenseSmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-_VYRcjkObUnT5ARTM7e4Rvw7Cyug5ho',
    appId: '1:1021851511933:web:de290bfb8acb3707af1514',
    messagingSenderId: '1021851511933',
    projectId: 'eliassprinksens',
    authDomain: 'eliassprinksens.firebaseapp.com',
    storageBucket: 'eliassprinksens.firebasestorage.app',
  );
}
